title: Bucket Ruckus Blog
description: The blog page for Bucket Ruckus Composting
footer_text: Copyright 2022 Bucket Ruckus
header_feature_image: ../uploads/background.jpg
header_text: Welcome to Bucket Ruckus Composting
header_text_color: "#deaa2b"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/logo70x65.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
